services:
  - type: web
    name: ajudefacil
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn ajudefacil.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ajudefacil.settings
