# Generated by Django 5.2.1 on 2025-06-11 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Recebedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Recebedor')),
                ('cpf_cnpj', models.CharField(max_length=20, verbose_name='CPF/CNPJ')),
                ('endereco', models.TextField(verbose_name='Endereço')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
            ],
        ),
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('quantidade', models.PositiveIntegerField()),
                ('quantidade_inicial', models.PositiveIntegerField(default=0, editable=False, help_text='Quantidade total que foi doada inicialmente')),
                ('local_entrega', models.CharField(max_length=100)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('distribuida', 'Distribuída')], default='pendente', max_length=20, verbose_name='Status')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doacoes.categoria')),
                ('doador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('doador', 'Doador'), ('voluntario', 'Voluntário'), ('administrador', 'Administrador')], max_length=20, verbose_name='Tipo de usuário')),
                ('cpf_cnpj', models.CharField(blank=True, max_length=20, null=True, verbose_name='CPF/CNPJ')),
                ('data_nascimento_fundacao', models.DateField(blank=True, null=True, verbose_name='Nascimento/Fundação')),
                ('endereco', models.TextField(blank=True, null=True, verbose_name='Endereço')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Distribuicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_distribuida', models.PositiveIntegerField()),
                ('data_distribuicao', models.DateTimeField(auto_now_add=True)),
                ('doacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doacoes.doacao')),
                ('recebedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doacoes.recebedor')),
            ],
        ),
    ]
