# Generated by Django 5.2.1 on 2025-06-13 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='doacao',
            name='local_entrega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doacoes.localentrega'),
        ),
    ]
